version: 2.1
jobs:
  build:
    machine:
      image: ubuntu-2004:current
    resource_class: large
    steps:
      - checkout
      - run: echo "Hello"
      - run: docker pull ruby:3.1.1
      - persist_to_workspace:
          root: .
          paths: ./
  downstream:        
    machine:
      image: ubuntu-2004:current
    resource_class: large
    steps:
      - attach_workspace:
          at: ./
      - run: arch
      - run: ls -la
      - run: docker run -it ruby:3.1.1 bin/bash
      - run: ruby -v
      - run: ls -la
      - run: arch

workflows:
  btd:
    jobs:
      - build
      - downstream:
          requires:
            - build
