version: 2.1
jobs:
  build:
    machine:
      image: ubuntu-2004:current
    resource_class: large
    steps:
      - checkout
      - run: echo "Hello"
      - run: docker pull cimg/ruby:3.1.1
      - run: ls -la
